maintainers:
 - alexellis
 - Waterdrips
 - utsavanand2

features:
 - dco_check
 - comments
 - pr_description_required

contributing_url: https://github.com/alexellis/k8s-on-raspbian/blob/master/CONTRIBUTING.md
